const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    selectFolder: () => ipcRenderer.invoke('select-folder'),
    readPackageJson: (path) => ipcRenderer.invoke('read-package-json', path),
    openFolder: (path) => ipcRenderer.invoke('open-folder', path),
    openTerminal: (path) => ipcRenderer.invoke('open-terminal', path),
    runNpmScript: (data) => ipcRenderer.invoke('run-npm-script', data),
    openVSCode: (path) => ipcRenderer.invoke('open-vscode', path),
    openExternal: (url) => ipcRenderer.invoke('open-external', url),
    minimize: () => ipcRenderer.invoke('window-minimize'),
    maximize: () => ipcRenderer.invoke('window-maximize'),
    close: () => ipcRenderer.invoke('window-close'),
    getAppVersion: () => ipcRenderer.invoke('get-app-version'),
    getConfig: () => ipcRenderer.invoke('get-config'),
    saveConfig: (config) => ipcRenderer.invoke('save-config', config),
    checkUpdates: () => ipcRenderer.invoke('check-updates'),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    createRelease: (data) => ipcRenderer.invoke('create-release', data),
    selectFile: (filters) => ipcRenderer.invoke('select-file', filters),
    readFile: (path) => ipcRenderer.invoke('read-file', path),
    saveFile: (data) => ipcRenderer.invoke('save-file', data),
    // Git API
    checkGitRepo: (path) => ipcRenderer.invoke('check-git-repo', path),
    gitStatus: (path) => ipcRenderer.invoke('git-status', path),
    gitAdd: (data) => ipcRenderer.invoke('git-add', data),
    gitCommit: (data) => ipcRenderer.invoke('git-commit', data),
    gitPush: (path) => ipcRenderer.invoke('git-push', path),
    gitPull: (path) => ipcRenderer.invoke('git-pull', path),
    gitLog: (path) => ipcRenderer.invoke('git-log', path),
    setLaunchAtStartup: (enabled) => ipcRenderer.invoke('set-launch-at-startup', enabled),
    setWindowState: (state) => ipcRenderer.invoke('set-window-state', state),
    setTrayMode: (enabled) => ipcRenderer.invoke('set-tray-mode', enabled),
});
